//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsfRecruimentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_UnionInfo
    {
        public string UnionID { get; set; }
        public string UnionName { get; set; }
        public string UpazilaCode { get; set; }
        public Nullable<decimal> IDCOLUnionID { get; set; }
        public string IDCOLUnionName { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_UpazillaInfo Common_UpazillaInfo { get; set; }
    }
}
