//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsfRecruimentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_CandidatesCVBank
    {
        public string CandidateID { get; set; }
        public string CandidateName { get; set; }
        public string CandidateFathersName { get; set; }
        public string CandidateMothersName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string NationalIDCard { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<bool> IsAnywhereInBd { get; set; }
        public string PreferredDepartment { get; set; }
        public string PreferredDistrictCode { get; set; }
        public string PreferredDistrictCode1 { get; set; }
        public string PreferredDistrictCode2 { get; set; }
        public string PresentDivisionCode { get; set; }
        public string PresentDistrictCode { get; set; }
        public string PresentUpazillaCode { get; set; }
        public string PresentUnionID { get; set; }
        public string PresentPoliceStation { get; set; }
        public string PresentPostOffice { get; set; }
        public string PresentStreetOrVillage { get; set; }
        public string PresentHouseNo { get; set; }
        public string PresentMobileNo { get; set; }
        public string PresentPhone { get; set; }
        public string PermanentDivisionCode { get; set; }
        public string PermanentDistrictCode { get; set; }
        public string PermanentUpazillaCode { get; set; }
        public string PermanentUnionID { get; set; }
        public string PermanentPoliceStation { get; set; }
        public string PermanentPostOffice { get; set; }
        public string PermanentStreetVillage { get; set; }
        public string PermanentHouseNo { get; set; }
        public string PermanentMobileNo { get; set; }
        public Nullable<bool> ComputerSkill_MSWord { get; set; }
        public Nullable<bool> ComputerSkill_MSExcel { get; set; }
        public Nullable<bool> ComputerSkill_MSPPoint { get; set; }
        public Nullable<bool> ComputerSkill_MobileApp { get; set; }
        public Nullable<bool> ComputerSkill_ERP { get; set; }
        public string ExtracurricularActivities { get; set; }
        public string SourcesOfJobInfo { get; set; }
        public string AppliedPosition { get; set; }
        public string CareerObjective { get; set; }
        public string ReferenceName1 { get; set; }
        public string ReferenceOrgNAddress1 { get; set; }
        public string ReferenceDesignation1 { get; set; }
        public string ReferenceContactNo1 { get; set; }
        public string ReferenceEmail1 { get; set; }
        public string ReferenceRelation1 { get; set; }
        public string ReferenceName2 { get; set; }
        public string ReferenceOrgNAddress2 { get; set; }
        public string ReferenceDesignation2 { get; set; }
        public string ReferenceContactNo2 { get; set; }
        public string ReferenceEmail2 { get; set; }
        public string ReferenceRelation2 { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<bool> IsRecordsSubmitted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> StatusChangedDate { get; set; }
        public string TrackingDistrictName { get; set; }
    
        public virtual Hrm_CandidatesCVBankExtension Hrm_CandidatesCVBankExtension { get; set; }
    }
}
