//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsfRecruimentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_CandidatesCVBankExtension
    {
        public string CandidateID { get; set; }
        public string DegreeName { get; set; }
        public string MajorSubject { get; set; }
        public string Board_University { get; set; }
        public string InstituteName { get; set; }
        public string PassingYear { get; set; }
        public string Grade { get; set; }
        public string ExamGrade { get; set; }
        public string Result { get; set; }
        public string Achievement { get; set; }
        public string DegreeName1 { get; set; }
        public string MajorSubject1 { get; set; }
        public string Board_University1 { get; set; }
        public string InstituteName1 { get; set; }
        public string PassingYear1 { get; set; }
        public string Grade1 { get; set; }
        public string ExamGrade1 { get; set; }
        public string Result1 { get; set; }
        public string Achievement1 { get; set; }
        public string DegreeName2 { get; set; }
        public string MajorSubject2 { get; set; }
        public string Board_University2 { get; set; }
        public string InstituteName2 { get; set; }
        public string PassingYear2 { get; set; }
        public string Grade2 { get; set; }
        public string ExamGrade2 { get; set; }
        public string Result2 { get; set; }
        public string Achievement2 { get; set; }
        public string DegreeName3 { get; set; }
        public string MajorSubject3 { get; set; }
        public string Board_University3 { get; set; }
        public string InstituteName3 { get; set; }
        public string PassingYear3 { get; set; }
        public string Grade3 { get; set; }
        public string ExamGrade3 { get; set; }
        public string Result3 { get; set; }
        public string Achievement3 { get; set; }
        public string DegreeName4 { get; set; }
        public string MajorSubject4 { get; set; }
        public string Board_University4 { get; set; }
        public string InstituteName4 { get; set; }
        public string PassingYear4 { get; set; }
        public string Grade4 { get; set; }
        public string ExamGrade4 { get; set; }
        public string Result4 { get; set; }
        public string Achievement4 { get; set; }
        public string TrainingName { get; set; }
        public string TrainingInstituteName { get; set; }
        public string TrainingInstituteAddress { get; set; }
        public string TrainingDuration { get; set; }
        public string TrainingYear { get; set; }
        public string TrainingAchievement { get; set; }
        public string TrainingName1 { get; set; }
        public string TrainingInstituteName1 { get; set; }
        public string TrainingInstituteAddress1 { get; set; }
        public string TrainingDuration1 { get; set; }
        public string TrainingYear1 { get; set; }
        public string TrainingAchievement1 { get; set; }
        public string TrainingName2 { get; set; }
        public string TrainingInstituteName2 { get; set; }
        public string TrainingInstituteAddress2 { get; set; }
        public string TrainingDuration2 { get; set; }
        public string TrainingYear2 { get; set; }
        public string TrainingAchievement2 { get; set; }
        public string TrainingName3 { get; set; }
        public string TrainingInstituteName3 { get; set; }
        public string TrainingInstituteAddress3 { get; set; }
        public string TrainingDuration3 { get; set; }
        public string TrainingYear3 { get; set; }
        public string TrainingAchievement3 { get; set; }
        public string TrainingName4 { get; set; }
        public string TrainingInstituteName4 { get; set; }
        public string TrainingInstituteAddress4 { get; set; }
        public string TrainingDuration4 { get; set; }
        public string TrainingYear4 { get; set; }
        public string TrainingAchievement4 { get; set; }
        public string ExperienceOrganization { get; set; }
        public string ExperienceOrganizationAddress { get; set; }
        public string ExperienceDesignation { get; set; }
        public string ExperienceDepartment { get; set; }
        public Nullable<System.DateTime> ExperienceFromDate { get; set; }
        public Nullable<System.DateTime> ExperienceToDate { get; set; }
        public string ExperienceAchievement { get; set; }
        public string ExperienceOrganization1 { get; set; }
        public string ExperienceOrganizationAddress1 { get; set; }
        public string ExperienceDesignation1 { get; set; }
        public string ExperienceDepartment1 { get; set; }
        public Nullable<System.DateTime> ExperienceFromDate1 { get; set; }
        public Nullable<System.DateTime> ExperienceToDate1 { get; set; }
        public string ExperienceAchievement1 { get; set; }
        public string ExperienceOrganization2 { get; set; }
        public string ExperienceOrganizationAddress2 { get; set; }
        public string ExperienceDesignation2 { get; set; }
        public string ExperienceDepartment2 { get; set; }
        public Nullable<System.DateTime> ExperienceFromDate2 { get; set; }
        public Nullable<System.DateTime> ExperienceToDate2 { get; set; }
        public string ExperienceAchievement2 { get; set; }
        public string ExperienceOrganization3 { get; set; }
        public string ExperienceOrganizationAddress3 { get; set; }
        public string ExperienceDesignation3 { get; set; }
        public string ExperienceDepartment3 { get; set; }
        public Nullable<System.DateTime> ExperienceFromDate3 { get; set; }
        public Nullable<System.DateTime> ExperienceToDate3 { get; set; }
        public string ExperienceAchievement3 { get; set; }
        public string ExperienceOrganization4 { get; set; }
        public string ExperienceOrganizationAddress4 { get; set; }
        public string ExperienceDesignation4 { get; set; }
        public string ExperienceDepartment4 { get; set; }
        public Nullable<System.DateTime> ExperienceFromDate4 { get; set; }
        public Nullable<System.DateTime> ExperienceToDate4 { get; set; }
        public string ExperienceAchievement4 { get; set; }
    
        public virtual Hrm_CandidatesCVBank Hrm_CandidatesCVBank { get; set; }
    }
}
