//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsfRecruimentApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RASolarERPEntities : DbContext
    {
        public RASolarERPEntities()
            : base("name=RASolarERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Common_DistrictInfo> Common_DistrictInfo { get; set; }
        public DbSet<Common_UpazillaInfo> Common_UpazillaInfo { get; set; }
        public DbSet<Common_DivisionInfo> Common_DivisionInfo { get; set; }
        public DbSet<Hrm_EducationInfo> Hrm_EducationInfo { get; set; }
        public DbSet<Hrm_MajorSubject> Hrm_MajorSubject { get; set; }
        public DbSet<Hrm_MaritalStatusInfo> Hrm_MaritalStatusInfo { get; set; }
        public DbSet<Hrm_ReligionInfo> Hrm_ReligionInfo { get; set; }
        public DbSet<Hrm_BloodGroupInfo> Hrm_BloodGroupInfo { get; set; }
        public DbSet<Common_UnionInfo> Common_UnionInfo { get; set; }
        public DbSet<Hrm_CandidatesCVBank> Hrm_CandidatesCVBank { get; set; }
        public DbSet<Hrm_CandidatesCVBankExtension> Hrm_CandidatesCVBankExtension { get; set; }
    }
}
